// Auto-generated from published Splendor card/noble data. See cards.data.test.ts for integrity checks.
import type { Card, Noble } from '../shared/types.js';

export const CARDS: Card[] = [
  { id: 't1-black-1', tier: 1, color: 'black', points: 0, cost: { blue: 1, green: 1, red: 1, white: 1 } },
  { id: 't1-black-2', tier: 1, color: 'black', points: 0, cost: { blue: 2, green: 1, red: 1, white: 1 } },
  { id: 't1-black-3', tier: 1, color: 'black', points: 0, cost: { blue: 2, red: 1, white: 2 } },
  { id: 't1-black-4', tier: 1, color: 'black', points: 0, cost: { black: 1, green: 1, red: 3 } },
  { id: 't1-black-5', tier: 1, color: 'black', points: 0, cost: { green: 2, red: 1 } },
  { id: 't1-black-6', tier: 1, color: 'black', points: 0, cost: { green: 2, white: 2 } },
  { id: 't1-black-7', tier: 1, color: 'black', points: 0, cost: { green: 3 } },
  { id: 't1-black-8', tier: 1, color: 'black', points: 1, cost: { blue: 4 } },
  { id: 't1-blue-1', tier: 1, color: 'blue', points: 0, cost: { black: 1, green: 1, red: 1, white: 1 } },
  { id: 't1-blue-2', tier: 1, color: 'blue', points: 0, cost: { black: 1, green: 1, red: 2, white: 1 } },
  { id: 't1-blue-3', tier: 1, color: 'blue', points: 0, cost: { green: 2, red: 2, white: 1 } },
  { id: 't1-blue-4', tier: 1, color: 'blue', points: 0, cost: { blue: 1, green: 3, red: 1 } },
  { id: 't1-blue-5', tier: 1, color: 'blue', points: 0, cost: { black: 2, white: 1 } },
  { id: 't1-blue-6', tier: 1, color: 'blue', points: 0, cost: { black: 2, green: 2 } },
  { id: 't1-blue-7', tier: 1, color: 'blue', points: 0, cost: { black: 3 } },
  { id: 't1-blue-8', tier: 1, color: 'blue', points: 1, cost: { red: 4 } },
  { id: 't1-white-1', tier: 1, color: 'white', points: 0, cost: { black: 1, blue: 1, green: 1, red: 1 } },
  { id: 't1-white-2', tier: 1, color: 'white', points: 0, cost: { black: 1, blue: 1, green: 2, red: 1 } },
  { id: 't1-white-3', tier: 1, color: 'white', points: 0, cost: { black: 1, blue: 2, green: 2 } },
  { id: 't1-white-4', tier: 1, color: 'white', points: 0, cost: { black: 1, blue: 1, white: 3 } },
  { id: 't1-white-5', tier: 1, color: 'white', points: 0, cost: { black: 1, red: 2 } },
  { id: 't1-white-6', tier: 1, color: 'white', points: 0, cost: { black: 2, blue: 2 } },
  { id: 't1-white-7', tier: 1, color: 'white', points: 0, cost: { blue: 3 } },
  { id: 't1-white-8', tier: 1, color: 'white', points: 1, cost: { green: 4 } },
  { id: 't1-green-1', tier: 1, color: 'green', points: 0, cost: { black: 1, blue: 1, red: 1, white: 1 } },
  { id: 't1-green-2', tier: 1, color: 'green', points: 0, cost: { black: 2, blue: 1, red: 1, white: 1 } },
  { id: 't1-green-3', tier: 1, color: 'green', points: 0, cost: { black: 2, blue: 1, red: 2 } },
  { id: 't1-green-4', tier: 1, color: 'green', points: 0, cost: { blue: 3, green: 1, white: 1 } },
  { id: 't1-green-5', tier: 1, color: 'green', points: 0, cost: { blue: 1, white: 2 } },
  { id: 't1-green-6', tier: 1, color: 'green', points: 0, cost: { blue: 2, red: 2 } },
  { id: 't1-green-7', tier: 1, color: 'green', points: 0, cost: { red: 3 } },
  { id: 't1-green-8', tier: 1, color: 'green', points: 1, cost: { black: 4 } },
  { id: 't1-red-1', tier: 1, color: 'red', points: 0, cost: { black: 1, blue: 1, green: 1, white: 1 } },
  { id: 't1-red-2', tier: 1, color: 'red', points: 0, cost: { black: 1, blue: 1, green: 1, white: 2 } },
  { id: 't1-red-3', tier: 1, color: 'red', points: 0, cost: { black: 2, green: 1, white: 2 } },
  { id: 't1-red-4', tier: 1, color: 'red', points: 0, cost: { black: 3, red: 1, white: 1 } },
  { id: 't1-red-5', tier: 1, color: 'red', points: 0, cost: { blue: 2, green: 1 } },
  { id: 't1-red-6', tier: 1, color: 'red', points: 0, cost: { red: 2, white: 2 } },
  { id: 't1-red-7', tier: 1, color: 'red', points: 0, cost: { white: 3 } },
  { id: 't1-red-8', tier: 1, color: 'red', points: 1, cost: { white: 4 } },
  { id: 't2-black-9', tier: 2, color: 'black', points: 1, cost: { blue: 2, green: 2, white: 3 } },
  { id: 't2-black-10', tier: 2, color: 'black', points: 1, cost: { black: 2, green: 3, white: 3 } },
  { id: 't2-black-11', tier: 2, color: 'black', points: 2, cost: { blue: 1, green: 4, red: 2 } },
  { id: 't2-black-12', tier: 2, color: 'black', points: 2, cost: { green: 5, red: 3 } },
  { id: 't2-black-13', tier: 2, color: 'black', points: 2, cost: { white: 5 } },
  { id: 't2-black-14', tier: 2, color: 'black', points: 3, cost: { black: 6 } },
  { id: 't2-blue-9', tier: 2, color: 'blue', points: 1, cost: { blue: 2, green: 2, red: 3 } },
  { id: 't2-blue-10', tier: 2, color: 'blue', points: 1, cost: { black: 3, blue: 2, green: 3 } },
  { id: 't2-blue-11', tier: 2, color: 'blue', points: 2, cost: { blue: 3, white: 5 } },
  { id: 't2-blue-12', tier: 2, color: 'blue', points: 2, cost: { black: 4, red: 1, white: 2 } },
  { id: 't2-blue-13', tier: 2, color: 'blue', points: 2, cost: { blue: 5 } },
  { id: 't2-blue-14', tier: 2, color: 'blue', points: 3, cost: { blue: 6 } },
  { id: 't2-white-9', tier: 2, color: 'white', points: 1, cost: { black: 2, green: 3, red: 2 } },
  { id: 't2-white-10', tier: 2, color: 'white', points: 1, cost: { blue: 3, red: 3, white: 2 } },
  { id: 't2-white-11', tier: 2, color: 'white', points: 2, cost: { black: 2, green: 1, red: 4 } },
  { id: 't2-white-12', tier: 2, color: 'white', points: 2, cost: { black: 3, red: 5 } },
  { id: 't2-white-13', tier: 2, color: 'white', points: 2, cost: { red: 5 } },
  { id: 't2-white-14', tier: 2, color: 'white', points: 3, cost: { white: 6 } },
  { id: 't2-green-9', tier: 2, color: 'green', points: 1, cost: { green: 2, red: 3, white: 3 } },
  { id: 't2-green-10', tier: 2, color: 'green', points: 1, cost: { black: 2, blue: 3, white: 2 } },
  { id: 't2-green-11', tier: 2, color: 'green', points: 2, cost: { black: 1, blue: 2, white: 4 } },
  { id: 't2-green-12', tier: 2, color: 'green', points: 2, cost: { blue: 5, green: 3 } },
  { id: 't2-green-13', tier: 2, color: 'green', points: 2, cost: { green: 5 } },
  { id: 't2-green-14', tier: 2, color: 'green', points: 3, cost: { green: 6 } },
  { id: 't2-red-9', tier: 2, color: 'red', points: 1, cost: { black: 3, red: 2, white: 2 } },
  { id: 't2-red-10', tier: 2, color: 'red', points: 1, cost: { black: 3, blue: 3, red: 2 } },
  { id: 't2-red-11', tier: 2, color: 'red', points: 2, cost: { blue: 4, green: 2, white: 1 } },
  { id: 't2-red-12', tier: 2, color: 'red', points: 2, cost: { black: 5, white: 3 } },
  { id: 't2-red-13', tier: 2, color: 'red', points: 2, cost: { black: 5 } },
  { id: 't2-red-14', tier: 2, color: 'red', points: 3, cost: { red: 6 } },
  { id: 't3-black-15', tier: 3, color: 'black', points: 3, cost: { blue: 3, green: 5, red: 3, white: 3 } },
  { id: 't3-black-16', tier: 3, color: 'black', points: 4, cost: { red: 7 } },
  { id: 't3-black-17', tier: 3, color: 'black', points: 4, cost: { black: 3, green: 3, red: 6 } },
  { id: 't3-black-18', tier: 3, color: 'black', points: 5, cost: { black: 3, red: 7 } },
  { id: 't3-blue-15', tier: 3, color: 'blue', points: 3, cost: { black: 5, green: 3, red: 3, white: 3 } },
  { id: 't3-blue-16', tier: 3, color: 'blue', points: 4, cost: { white: 7 } },
  { id: 't3-blue-17', tier: 3, color: 'blue', points: 4, cost: { black: 3, blue: 3, white: 6 } },
  { id: 't3-blue-18', tier: 3, color: 'blue', points: 5, cost: { blue: 3, white: 7 } },
  { id: 't3-white-15', tier: 3, color: 'white', points: 3, cost: { black: 3, blue: 3, green: 3, red: 5 } },
  { id: 't3-white-16', tier: 3, color: 'white', points: 4, cost: { black: 7 } },
  { id: 't3-white-17', tier: 3, color: 'white', points: 4, cost: { black: 6, red: 3, white: 3 } },
  { id: 't3-white-18', tier: 3, color: 'white', points: 5, cost: { black: 7, white: 3 } },
  { id: 't3-green-15', tier: 3, color: 'green', points: 3, cost: { black: 3, blue: 3, red: 3, white: 5 } },
  { id: 't3-green-16', tier: 3, color: 'green', points: 4, cost: { blue: 7 } },
  { id: 't3-green-17', tier: 3, color: 'green', points: 4, cost: { blue: 6, green: 3, white: 3 } },
  { id: 't3-green-18', tier: 3, color: 'green', points: 5, cost: { blue: 7, green: 3 } },
  { id: 't3-red-15', tier: 3, color: 'red', points: 3, cost: { black: 3, blue: 5, green: 3, white: 3 } },
  { id: 't3-red-16', tier: 3, color: 'red', points: 4, cost: { green: 7 } },
  { id: 't3-red-17', tier: 3, color: 'red', points: 4, cost: { blue: 3, green: 6, red: 3 } },
  { id: 't3-red-18', tier: 3, color: 'red', points: 5, cost: { green: 7, red: 3 } },
];

export const NOBLES: Noble[] = [
  { id: 'noble-1', points: 3, requirement: { red: 4, green: 4 } },
  { id: 'noble-2', points: 3, requirement: { green: 4, blue: 4 } },
  { id: 'noble-3', points: 3, requirement: { blue: 4, white: 4 } },
  { id: 'noble-4', points: 3, requirement: { white: 4, black: 4 } },
  { id: 'noble-5', points: 3, requirement: { black: 4, red: 4 } },
  { id: 'noble-6', points: 3, requirement: { red: 3, green: 3, blue: 3 } },
  { id: 'noble-7', points: 3, requirement: { blue: 3, green: 3, white: 3 } },
  { id: 'noble-8', points: 3, requirement: { blue: 3, white: 3, black: 3 } },
  { id: 'noble-9', points: 3, requirement: { white: 3, black: 3, red: 3 } },
  { id: 'noble-10', points: 3, requirement: { black: 3, red: 3, green: 3 } },
];
